---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(ggcorrplot)
library(viridis)
library(sjPlot)
library(brainconn)
```

```{r -- 1. load behavioral dataset }
  data_dir = "~/[INSERT PATH HERE]/Manuscript/DATA/"

df_behav = read.csv(paste0(data_dir, "Data -- Demographic & Behavioral Data.csv"))
  df_behav$Sex_n = as.numeric(factor(df_behav$Sex))
```

```{r -- 2. calculate descriptive statistics [Table 1]}

table(df_behav$Sex)

apply(subset(df_behav, select = -c(Participant, Sex, Sex_n)), 2, function (x) {
  data.frame(mu = mean(x, na.rm = TRUE),
             sd = sd(x, na.rm = TRUE),
             range = range(x, na.rm = TRUE))
})

```

```{r -- 3. load atlas labels }
  data_dir = "~/[INSERT PATH HERE]/Manuscript/DATA/"

WM_ROIs = read.csv(paste0(data_dir, "Atlases/WM_ROIs.csv"))
GM_ROIs = read.csv(paste0(data_dir, "Atlases/GM_ROIs.csv"))

```

```{r -- 4. load participant WM-GM connectivity matrices }

M_wide = list()

  folder = "~/[INSERT PATH HERE]/Manuscript/DATA/WM_GM_m/"

file_names <- list.files(folder)
  
  # omit repeated files
  exclude_patterns = c("b_")
  filtered_files = file_names[!grepl(exclude_patterns, file_names)]

for (file in filtered_files) {
  M = read.csv(paste0(folder, file))
  M = data.frame(M[-c(1)])
    
  colnames(M) = t(GM_ROIs$ROI)
  rownames(M) = as.matrix(WM_ROIs$ROI)
  
  M_wide[[file]] = M
}

names(M_wide) = gsub("FCM_GW_RC2", "RC2", names(M_wide))
names(M_wide) = gsub("_REST.csv", "", names(M_wide))

```

```{r -- 5. visualize group-averaged white- and gray-matter functional connectivity [Supplemental Figure 1]}

M_mean = Reduce("+", M_wide)/length(M_wide)

ggcorrplot(M_mean) +
  #geom_tile(color = "black") +
  scale_fill_gradientn(colors = viridis(256, option = 'H'), limits = c(-0.4, 0.8)) +
 theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10),
       axis.text.y = element_text(size = 10),
       panel.grid = element_blank())

```

```{r -- 6. filter connectivity values by WM tracts }

  #### tract of interest -- left uncinate fasciculus
M_wide_L_UF = lapply(M_wide, function(m) m[c("UF_L"),])


  #### tracts for control comparisons 
M_wide_R_UF = lapply(M_wide, function(m) m[c("UF_R"),]) # right uncinate fasciculus
M_wide_L_SS = lapply(M_wide, function(m) m[c("SS_L"),]) # left saggital stratum
M_wide_L_CCG = lapply(M_wide, function(m) m[c("CCG_L"),]) # left cingulum

```

```{r -- 7. transform & collapse data across individual matrices }

M_interest = M_wide_L_UF ## input tract of interest

M_tf = lapply(M_interest, function(m) tibble::rownames_to_column(m, "ROI"))

M_long = lapply(M_tf, function(m) reshape2::melt(m, id.vars = "ROI"))
  M_long = lapply(M_long, function(m) {
    colnames(m) = c("ROI_from", "ROI_to", "r")
    m})

  # ROI pairs
  M_sample = M_long[[1]]
ROI_ROI_pair = M_sample[c("ROI_from", "ROI_to")]
  ROI_ROI_pair$ROI_pair = paste0(ROI_ROI_pair$ROI_from, "___", ROI_ROI_pair$ROI_to)
  
  # collapsing data
  M_coef = lapply(M_long, function(m) m[3])
  df_coef = data.frame(M_sample[c("ROI_from", "ROI_to")],
                      do.call(cbind, M_coef)) # column as participant / row as ROI

df_coef_t = data.frame(t(data.frame(df_coef[-c(1:2)]))) # row as participant / column as ROI
  colnames(df_coef_t) = t(paste0(df_coef$ROI_from, "___", df_coef$ROI_to))

```

```{r - 8. load data for analysis }

df_conn = data.frame(Participant = names(M_coef), df_coef_t)
  rownames(df_conn) = NULL
  df_conn_id = data.frame(Participant = df_conn$Participant)
  
df_var = merge(df_conn_id, df_behav, by = c("Participant"), complete = TRUE)
  df_var_id = data.frame(Participant = df_var$Participant)

df_conn = merge(df_var_id, df_conn, by = c("Participant"), complete = TRUE)
  df_conn = data.frame(apply(df_conn[-c(1)], 2, function(x) as.numeric(x)))
  rownames(df_conn) = NULL
  
```

```{r -- 9. visualize distributions of reading scores & correlation [Figure 3a+b] }

df_WJ = df_var[c("WJ_BasicReading_Std", "WJ_PassageComp_Std")]

rcorr(as.matrix(df_WJ))

df_long <- df_WJ %>%
  pivot_longer(cols = c(WJ_BasicReading_Std, WJ_PassageComp_Std), names_to = "Test", values_to = "Score")

mean_df <- df_long %>%
  group_by(Test) %>%
  summarise(mean_score = mean(Score, na.rm = TRUE))

ggplot(df_long, aes(x = Score, fill = Test, color = Test)) +
  geom_histogram(aes(y = ..count..), position = "identity", alpha = 0.4, bins = 30) +
  scale_fill_manual(values = c("WJ_BasicReading_Std" = "#2f5597",
                               "WJ_PassageComp_Std" = "#323f51")) +
  scale_color_manual(values = c("WJ_BasicReading_Std" = "#2f5597",
                                "WJ_PassageComp_Std" = "#323f51")) +
  #geom_density(aes(y = ..count..), alpha = 0.2, size = 1) +
  labs(title = "WJ Scores",
           y = "Count") +
  theme_bw() +
  theme(
    axis.text.x = element_text(size = 12),  # x-axis tick label size
    axis.text.y = element_text(size = 12)   # y-axis tick label size
  )

ggplot(df_WJ, aes(x = WJ_BasicReading_Std, y = WJ_PassageComp_Std)) +
  geom_point(alpha = 0.7) +
  geom_smooth(method = "lm", formula = y ~ x, color = "black", se = TRUE) +
  theme_bw() +
  theme(
    axis.text.x = element_text(size = 12),  # x-axis tick label size
    axis.text.y = element_text(size = 12)   # y-axis tick label size
  ) +
  labs(title = "Relationship Between WJ BR and PC",
       x = "WJ Basic Reading",
       y = "WJ Passage Comprehension")

```

```{r -- 10. residualize WM-GM functional connectivity values }

  brain = data.frame(df_conn)

r_brain = data.frame(apply(brain, 2, function(x) {
  resid(lm(x ~ as.numeric(mean.FD_Power) + Handedness_Percentile + Age + Sex, data = df_var)) }))

```

```{r -- 11. filter BA GM ROIs based on structural circuitry }

GM_ROIs = c("BA38", "BA36", "BA35", "BA25", "BA10", "BA11", "BA45", "BA47") 
  pattern = paste0("UF_L___(", paste(GM_ROIs, collapse = "|"), ")_L")

r_brain_ROIs = r_brain[ , grepl(pattern, names(r_brain))]

```

```{r -- 12. run regression - RC = WR x WM-GM ROIs [Table 2] }

plot_i = data.frame(NULL)

for (i in 1:ncol(r_brain_ROIs)) {
  
  m = summary(lm(scale(WJ_PassageComp_Std) ~
                   1 +
                   
                   scale(WJ_BasicReading_Std)*scale(r_brain_ROIs[,i]) +
                   
                   Age +
                   Sex,
                 
                   data = df_var))
  
  plot_i[i, 1] = colnames(r_brain_ROIs)[i]
  plot_i[i, 2] = round(m$coefficients[6, 1], 4) # b val
  plot_i[i, 3] = round(m$coefficients[6, 2], 4) # se val
  plot_i[i, 4] = round(m$coefficients[6, 4], 6) # p val
  
}
  
  colnames(plot_i) = c("ROI_pair", "b", "se", "p")
  
plot_i$p_fdr = p.adjust(plot_i$p, "fdr", ncol(r_brain_ROIs))
plot_i[order(plot_i$b),]

```

```{r - 13. visualize ROI-based connectivity matrix [Figure 3a] }
  data_dir = "~/[INSERT PATH HERE]/Manuscript/DATA/"

Brd_Eve_Atlases = read.csv(paste0(data_dir, "Atlases/Brd_Eve_Atlases _ ROIs.csv"))
df_ROIs_M = read.csv(paste0(data_dir, "Brd_Eve ROI Connectivity _ M.csv"), header = TRUE)

M_plot = df_ROIs_M
  M_plot = M_plot[-c(1)]
  rownames(M_plot) = t(colnames(M_plot))

df_x = apply(M_plot, 1, as.integer)
df_x = data.frame(df_x)
  colnames(df_x) <- paste0("V", seq_len(ncol(df_x)))
  rownames(df_x) <- paste0(seq_len(ncol(df_x)))

brainconn(atlas ="Brd_Eve_Atlases",
          conmat = df_x,
          node.size = 7,
          node.color = c("black"),
          edge.width = 1.5,
          background.alpha = 0.6,
          view="ortho")

version
```

```{r -- 14. visualize interaction plots [Figure 3b] }
set_theme(base = theme_bw())
  #qr.matrix <- function(x, ...) qr.default(x, ...)

df_var$ROI_1 = as.numeric(scale(r_brain_ROIs$UF_L___BA38_L))
df_var$ROI_2 = as.numeric(scale(r_brain_ROIs$UF_L___BA36_L))
df_var$ROI_3 = as.numeric(scale(r_brain_ROIs$UF_L___BA35_L))
df_var$ROI_4 = as.numeric(scale(r_brain_ROIs$UF_L___BA47_L))
df_var$ROI_5 = as.numeric(scale(r_brain_ROIs$UF_L___BA45_L))
df_var$WJ_BR = df_var$WJ_BasicReading_Std
df_var$WJ_PC = df_var$WJ_PassageComp_Std

  # regression
fit = lm(WJ_PC ~ WJ_BR*ROI_1 + Age + Sex, data = df_var)
  plot_model(fit, type = "int", mdrt.values = "meansd")

```
